import { motion } from 'framer-motion'

export default function WhatYoureSeeing() {
  return (
    <div className="mx-auto max-w-5xl w-full">
      <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight">What You’re Seeing</h2>
      <motion.div
        initial={{ scaleX: 0 }}
        animate={{ scaleX: 1 }}
        transition={{ duration: 0.5, ease: 'easeOut' }}
        className="mt-2 mb-5 h-1.5 w-52 rounded-full bg-gradient-to-r from-accent to-accent2 origin-left"
      />
      <div className="surface p-6">
        <ul className="list-disc pl-5">
          <li>This entire presentation was:
            <ul className="list-disc pl-5 mt-2 text-[var(--muted)]">
              <li>Written in Markdown</li>
              <li>Generated by Copilot</li>
            </ul>
          </li>
          <li className="mt-3">No manual PowerPoint slides</li>
          <li className="mt-1">Just AI + React + a bit of iteration</li>
        </ul>
      </div>
    </div>
  )
}

